---
version: "3.7"

x-build-common: &build-common
  build:
    context: .
    dockerfile: Dockerfile
    target: development

x-app-common: &app-common
  extra_hosts:
    - "host.docker.internal:host-gateway"
  stdin_open: true
  tty: true
  # entrypoint: script/docker-entrypoint-development.sh
  volumes:
    - .:/app
    - bundler:/bundler

services:
  web:
    <<: [*build-common, *app-common]
    depends_on:
      - tailwind
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "3000:3000"
    environment:
      ENVIRONMENT: development
      HISTFILE: /app/.zsh_history
  
  guard:
    <<: [*build-common, *app-common]
    depends_on:
      - web
    command: bundle exec guard
    ports:
      - "35729:35729"

  tailwind:
    <<: [*build-common, *app-common]
    command: bundle exec bin/rails tailwindcss:watch
 
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

volumes:
  bundler:
  mailhog:
  redis-data:
